name: datatree-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black
  - codecov
  - flake8
  - h5netcdf
  - netcdf4
  - pooch
  - pytest
  - pytest-cov
  - python>=3.8
  - xarray>=2022.6.0
  - zarr
